export const languages = [
  "Common",
  "Dwarvish",
  "Elvish",
  "Giant",
  "Gnomish",
  "Goblin",
  "Halfling",
  "Orc",
  "Abyssal",
  "Celestial",
  "Draconic",
  "Deep Speech",
  "Infernal",
  "Primordial",
  "Sylvan",
  "Undercommon",
];
export const conditions = [
  "Blinded",
  "Charmed",
  "Deafened",
  "Frightened",
  "Grappled",
  "Incapacitated",
  "Invisible",
  "Paralyzed",
  "Petrified",
  "Poisoned",
  "Prone",
  "Restrained",
  "Stunned",
  "Unconscious",
  "Exhaustion",
];
export const skills = [
  "Acrobatics",
  "Sleight of Hand",
  "Stealth",
  "Arcana",
  "History",
  "Investigation",
  "Nature",
  "Religion",
  "Animal Handling",
  "Insight",
  "Medicine",
  "Perception",
  "Survival",
  "Deception",
  "Intimidation",
  "Performance",
  "Persuasion",
];
export const damageType = [
  "Slashing",
  "Piercing",
  "Bludgeoning",
  "Poison",
  "Acid",
  "Fire",
  "Cold",
  "Radiant",
  "Necrotic",
  "Lightning",
  "Thunder",
  "Force",
  "Psychic",
];

export const size = ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"];

export const challengeRating = ["0", "1/8", "1/4", "1/2", 
"1", "2", "3", "4", "5","6","7","8","9","10",
"11", "12", "13", "14", "15","16","17","18","19","20",
"21", "22", "23", "24", "25","26","27","28","29","30"];

export const type = [
  "Aberration",
  "Beast",
  "Celestial",
  "Construct",
  "Dragon",
  "Elemental",
  "Fey",
  "Fiend",
  "Giant",
  "Humanoid",
  "Monstrosity",
  "Ooze",
  "Plant",
  "Undead",
];

export const states = ["STR", "DEX", "CON", "INT", "WIS", "CHA"];
